# Создайте матрицу 3 на 3, заполненную числами от 1 до 9
Прибавьте к ней матрицу с единицами на диагонале
Умножьте полученную матрицу на вектор (1, 2, 3)
Посчитайте обратную матрицу к полученной матрице

In [1]:
import numpy as np

In [3]:
m = np.array([[1,2,3],
              [4,5,6], 
              [7,8,9]])
m_one = np.eye(3)

In [4]:
sum_m = m + m_one
sum_m

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [5]:
mul = sum_m * np.array([1,2,3])
mul

array([[ 2.,  4.,  9.],
       [ 4., 12., 18.],
       [ 7., 16., 30.]])

In [6]:
inv = np.linalg.inv(mul)
inv

array([[-6.        , -2.        ,  3.        ],
       [-0.5       ,  0.25      ,  0.        ],
       [ 1.66666667,  0.33333333, -0.66666667]])

In [7]:
inv @ mul

array([[ 1.00000000e+00, -7.10542736e-15, -1.42108547e-14],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])